-- MySQL Script generated by MySQL Workbench
-- Sat Nov  4 22:03:08 2023
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema sasit
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `sasit` ;

-- -----------------------------------------------------
-- Schema sasit
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `sasit` DEFAULT CHARACTER SET utf8 ;
USE `sasit` ;

-- -----------------------------------------------------
-- Table `sasit`.`student_profile`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `sasit`.`student_profile` ;

CREATE TABLE IF NOT EXISTS `sasit`.`student_profile` (
  `std_id` INT NOT NULL,
  `std_firstname` VARCHAR(45) NOT NULL,
  `std_lastname` VARCHAR(45) NOT NULL,
  `std_major` VARCHAR(5) NOT NULL,
  `std_email` VARCHAR(50) NOT NULL,
  PRIMARY KEY (`std_id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `sasit`.`admin_profile`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `sasit`.`admin_profile` ;

CREATE TABLE IF NOT EXISTS `sasit`.`admin_profile` (
  `admin_id` INT NOT NULL,
  `admin_firstname` VARCHAR(45) NOT NULL,
  `admin_lastname` VARCHAR(45) NOT NULL,
  `admin_username` VARCHAR(45) NOT NULL,
  `admin_password` VARCHAR(256) NOT NULL,
  PRIMARY KEY (`admin_id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `sasit`.`staff_profile`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `sasit`.`staff_profile` ;

CREATE TABLE IF NOT EXISTS `sasit`.`staff_profile` (
  `staff_id` INT NOT NULL,
  `staff_firstname` VARCHAR(45) NOT NULL,
  `staff_lastname` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`staff_id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `sasit`.`lecturer`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `sasit`.`lecturer` ;

CREATE TABLE IF NOT EXISTS `sasit`.`lecturer` (
  `lecturer_id` INT NOT NULL,
  `lecturer_firstname` VARCHAR(45) NOT NULL,
  `lecturer_lastname` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`lecturer_id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `sasit`.`subject`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `sasit`.`subject` ;

CREATE TABLE IF NOT EXISTS `sasit`.`subject` (
  `subject_id` INT NOT NULL,
  `subject_title` VARCHAR(10) NOT NULL,
  `subject_description` VARCHAR(100) NOT NULL,
  PRIMARY KEY (`subject_id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `sasit`.`enrollment`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `sasit`.`enrollment` ;

CREATE TABLE IF NOT EXISTS `sasit`.`enrollment` (
  `student_profile_std_id` INT NOT NULL,
  `subject_subject_id` INT NOT NULL,
  `class_id` INT NOT NULL,
  `academic year` INT NOT NULL,
  `semester` INT NOT NULL,
  `sec` INT NOT NULL,
  INDEX `fk_student_profile_has_subject_subject1_idx` (`subject_subject_id` ASC) VISIBLE,
  INDEX `fk_student_profile_has_subject_student_profile_idx` (`student_profile_std_id` ASC) VISIBLE,
  PRIMARY KEY (`class_id`),
  CONSTRAINT `fk_student_profile_has_subject_student_profile`
    FOREIGN KEY (`student_profile_std_id`)
    REFERENCES `sasit`.`student_profile` (`std_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_student_profile_has_subject_subject1`
    FOREIGN KEY (`subject_subject_id`)
    REFERENCES `sasit`.`subject` (`subject_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `sasit`.`title`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `sasit`.`title` ;

CREATE TABLE IF NOT EXISTS `sasit`.`title` (
  `title_id` INT NOT NULL,
  `title` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`title_id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `sasit`.`scores`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `sasit`.`scores` ;

CREATE TABLE IF NOT EXISTS `sasit`.`scores` (
  `class_id` INT NOT NULL,
  `scores` FLOAT NOT NULL,
  `note` VARCHAR(400) NOT NULL,
  `score_id` VARCHAR(45) NOT NULL,
  `title_title_id` INT NOT NULL,
  `last_update` DATETIME NOT NULL,
  INDEX `fk_classes_has_student_profile_classes1_idx` (`class_id` ASC) VISIBLE,
  PRIMARY KEY (`score_id`),
  INDEX `fk_scores_title1_idx` (`title_title_id` ASC) VISIBLE,
  CONSTRAINT `fk_classes_has_student_profile_classes1`
    FOREIGN KEY (`class_id`)
    REFERENCES `sasit`.`enrollment` (`class_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_scores_title1`
    FOREIGN KEY (`title_title_id`)
    REFERENCES `sasit`.`title` (`title_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `sasit`.`classes_supervisor`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `sasit`.`classes_supervisor` ;

CREATE TABLE IF NOT EXISTS `sasit`.`classes_supervisor` (
  `classes_class_id` INT NOT NULL,
  `lecturer_lecturer_id` INT NOT NULL,
  PRIMARY KEY (`classes_class_id`, `lecturer_lecturer_id`),
  INDEX `fk_classes_has_lecturer_lecturer1_idx` (`lecturer_lecturer_id` ASC) VISIBLE,
  INDEX `fk_classes_has_lecturer_classes1_idx` (`classes_class_id` ASC) VISIBLE,
  CONSTRAINT `fk_classes_has_lecturer_classes1`
    FOREIGN KEY (`classes_class_id`)
    REFERENCES `sasit`.`enrollment` (`class_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_classes_has_lecturer_lecturer1`
    FOREIGN KEY (`lecturer_lecturer_id`)
    REFERENCES `sasit`.`lecturer` (`lecturer_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `sasit`.`staff_supervisor`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `sasit`.`staff_supervisor` ;

CREATE TABLE IF NOT EXISTS `sasit`.`staff_supervisor` (
  `staff_profile_staff_id` INT NOT NULL,
  `classes_class_id` INT NOT NULL,
  PRIMARY KEY (`staff_profile_staff_id`, `classes_class_id`),
  INDEX `fk_staff_profile_has_classes_classes1_idx` (`classes_class_id` ASC) VISIBLE,
  INDEX `fk_staff_profile_has_classes_staff_profile1_idx` (`staff_profile_staff_id` ASC) VISIBLE,
  CONSTRAINT `fk_staff_profile_has_classes_staff_profile1`
    FOREIGN KEY (`staff_profile_staff_id`)
    REFERENCES `sasit`.`staff_profile` (`staff_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_staff_profile_has_classes_classes1`
    FOREIGN KEY (`classes_class_id`)
    REFERENCES `sasit`.`enrollment` (`class_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
