-- MySQL Script generated by MySQL Workbench
-- Wed Jan 17 22:47:39 2024
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema sasit
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `sasit` ;

-- -----------------------------------------------------
-- Schema sasit
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `sasit` DEFAULT CHARACTER SET utf8 ;
USE `sasit` ;

-- -----------------------------------------------------
-- Table `sasit`.`student_profile`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `sasit`.`student_profile` (
  `std_id` BIGINT(20) NOT NULL,
  `std_firstname` VARCHAR(45) NOT NULL,
  `std_lastname` VARCHAR(45) NOT NULL,
  `std_major` VARCHAR(5) NOT NULL,
  `std_email` VARCHAR(50) NOT NULL,
  PRIMARY KEY (`std_id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `sasit`.`admin_profile`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `sasit`.`admin_profile` (
  `admin_id` INT NOT NULL AUTO_INCREMENT,
  `admin_firstname` VARCHAR(45) NOT NULL,
  `admin_lastname` VARCHAR(45) NOT NULL,
  `admin_username` VARCHAR(45) NOT NULL,
  `admin_password` VARCHAR(256) NOT NULL,
  PRIMARY KEY (`admin_id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `sasit`.`staff_profile`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `sasit`.`staff_profile` (
  `staff_id` BIGINT(20) NOT NULL,
  `staff_firstname` VARCHAR(45) NOT NULL,
  `staff_lastname` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`staff_id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `sasit`.`lecturer`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `sasit`.`lecturer` (
  `lecturer_id` BIGINT(20) NOT NULL,
  `lecturer_firstname` VARCHAR(45) NOT NULL,
  `lecturer_lastname` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`lecturer_id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `sasit`.`subject`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `sasit`.`subject` (
  `subject_id` VARCHAR(10) NOT NULL,
  `subject_title` VARCHAR(100) NOT NULL,
  `subject_description` VARCHAR(600) NOT NULL,
  PRIMARY KEY (`subject_id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `sasit`.`title`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `sasit`.`title` (
  `title_id` INT NOT NULL AUTO_INCREMENT,
  `title` VARCHAR(250) NOT NULL,
  PRIMARY KEY (`title_id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `sasit`.`classes`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `sasit`.`classes` (
  `subject_id` VARCHAR(10) NOT NULL,
  `class_id` INT NOT NULL AUTO_INCREMENT,
  `academic_year` INT NOT NULL,
  `semester` INT NOT NULL,
  `sec` INT NOT NULL,
  INDEX `fk_classes_subject1_idx` (`subject_id` ASC) VISIBLE,
  PRIMARY KEY (`class_id`),
  CONSTRAINT `fk_classes_subject1`
    FOREIGN KEY (`subject_id`)
    REFERENCES `sasit`.`subject` (`subject_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `sasit`.`enrollments`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `sasit`.`enrollments` (
  `student_id` BIGINT(20) NOT NULL,
  `class_id` INT NOT NULL,
  `enrollment_id` INT NOT NULL AUTO_INCREMENT,
  INDEX `fk_student_profile_has_classes_classes1_idx` (`class_id` ASC) VISIBLE,
  INDEX `fk_student_profile_has_classes_student_profile1_idx` (`student_id` ASC) VISIBLE,
  PRIMARY KEY (`enrollment_id`),
  CONSTRAINT `fk_student_profile_has_classes_student_profile1`
    FOREIGN KEY (`student_id`)
    REFERENCES `sasit`.`student_profile` (`std_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_student_profile_has_classes_classes1`
    FOREIGN KEY (`class_id`)
    REFERENCES `sasit`.`classes` (`class_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `sasit`.`scores`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `sasit`.`scores` (
  `scores` FLOAT NOT NULL,
  `note` VARCHAR(400) NULL,
  `score_id` INT NOT NULL AUTO_INCREMENT,
  `title_id` INT NOT NULL,
  `last_update` DATETIME NOT NULL,
  `enrollment_id` INT NOT NULL,
  PRIMARY KEY (`score_id`),
  INDEX `fk_scores_title1_idx` (`title_id` ASC) VISIBLE,
  INDEX `fk_scores_enrollment1_idx` (`enrollment_id` ASC) VISIBLE,
  CONSTRAINT `fk_scores_title1`
    FOREIGN KEY (`title_id`)
    REFERENCES `sasit`.`title` (`title_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_scores_enrollment1`
    FOREIGN KEY (`enrollment_id`)
    REFERENCES `sasit`.`enrollments` (`enrollment_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `sasit`.`classes_supervisor`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `sasit`.`classes_supervisor` (
  `lecturer_id` BIGINT(20) NOT NULL,
  `class_id` INT NOT NULL,
  PRIMARY KEY (`lecturer_id`, `class_id`),
  INDEX `fk_lecturer_has_classes_classes1_idx` (`class_id` ASC) VISIBLE,
  INDEX `fk_lecturer_has_classes_lecturer1_idx` (`lecturer_id` ASC) VISIBLE,
  CONSTRAINT `fk_lecturer_has_classes_lecturer1`
    FOREIGN KEY (`lecturer_id`)
    REFERENCES `sasit`.`lecturer` (`lecturer_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_lecturer_has_classes_classes1`
    FOREIGN KEY (`class_id`)
    REFERENCES `sasit`.`classes` (`class_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `sasit`.`staff_supervisor`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `sasit`.`staff_supervisor` (
  `class_id` INT NOT NULL,
  `staff_id` BIGINT(20) NOT NULL,
  PRIMARY KEY (`class_id`, `staff_id`),
  INDEX `fk_classes_has_staff_profile_staff_profile1_idx` (`staff_id` ASC) VISIBLE,
  INDEX `fk_classes_has_staff_profile_classes1_idx` (`class_id` ASC) VISIBLE,
  CONSTRAINT `fk_classes_has_staff_profile_classes1`
    FOREIGN KEY (`class_id`)
    REFERENCES `sasit`.`classes` (`class_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_classes_has_staff_profile_staff_profile1`
    FOREIGN KEY (`staff_id`)
    REFERENCES `sasit`.`staff_profile` (`staff_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
